[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

[env:esp32doit-devkit-v1]

[env:esp32doit-devkit-v1-ota]
upload_protocol = espota
upload_port = hydrowash-esp32.local
upload_flags =
    --timeout=30
